on: workflow_dispatch

jobs:
  deploy_docker:
    name: "Deploy Docker"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Release.txt
          tag_name: yep2
          target_commitish: test
          make_latest: true

